module ContestSettings

#========================================================#
#=================== GENERAL SETTINGS ===================#
#========================================================#

#=================#
#===== MISC =====#
#=================#
SELECTED_POKEMON_VARIABLE = 32 #used for selecting a pokemon to enter
SELECTED_POKEMON_NAME_VARIABLE = 33 #needed for selecting a pokemon

TELEPORT_AFTER_CONTEST = nil

#=================#
#==== RIBBONS ====#
#=================#
#set the rewarded ribbon based on rank and type of contest
RIBBON_NORMAL_COOL   = :SINNOHCOOL
RIBBON_NORMAL_BEAUTY = :SINNOHBEAUTY
RIBBON_NORMAL_CUTE   = :SINNOHCUTE
RIBBON_NORMAL_SMART  = :SINNOHSMART
RIBBON_NORMAL_TOUGH  = :SINNOHTOUGH

RIBBON_GREAT_COOL   = :SINNOHCOOLSUPER
RIBBON_GREAT_BEAUTY = :SINNOHBEAUTYSUPER
RIBBON_GREAT_CUTE   = :SINNOHCUTESUPER
RIBBON_GREAT_SMART  = :SINNOHSMARTSUPER
RIBBON_GREAT_TOUGH  = :SINNOHTOUGHSUPER

RIBBON_ULTRA_COOL   = :SINNOHCOOLHYPER
RIBBON_ULTRA_BEAUTY = :SINNOHBEAUTYHYPER
RIBBON_ULTRA_CUTE   = :SINNOHCUTEHYPER
RIBBON_ULTRA_SMART  = :SINNOHSMARTHYPER
RIBBON_ULTRA_TOUGH  = :SINNOHTOUGHHYPER

RIBBON_MASTER_COOL   = :SINNOHCOOLMASTER
RIBBON_MASTER_BEAUTY = :SINNOHBEAUTYMASTER
RIBBON_MASTER_CUTE   = :SINNOHCUTEMASTER
RIBBON_MASTER_SMART  = :SINNOHSMARTMASTER
RIBBON_MASTER_TOUGH  = :SINNOHTOUGHMASTER

PRIZE_POOL_NORMAL = [:LOVEBALL, :LUREBALL, :MOONBALL, :REPEATBALL, :POKEBALL, :DURINBERRY, :MAGOSTBERRY, :ORANBERRY, :NOMELBERRY, :PINAPBERRY, :RAZZBERRY]
PRIZE_POOL_GREAT = [:DIVEBALL, :DIVEBALL, :FASTBALL, :FASTBALL, :HEALBALL, :HEALBALL, :PUREINCENSE, :SOOTHEBELL, :GREATBALL, :GREATBALL, :NANABBERRY, :NANABBERRY, :PAMTREBERRY, :PAMTREBERRY]
PRIZE_POOL_ULTRA = [:DESTINYKNOT, :DREAMBALL, :FRIENDBALL, :HEAVYBALL, :QUICKBALL, :ULTRABALL]
PRIZE_POOL_MASTER = [:ABILITYCAPSULE, :BALMMUSHROOM, :BALMMUSHROOM, :LUXURYBALL,  :LUXURYBALL,  :LUXURYBALL, :RARECANDY]

end #module ContestSettings