class Scene_Credits
  #hash that holds the names in credits that have graphics to display
  #this has also holds the name of the graphics
  #syntax:
  #{ "Name in credits" => "file name" }
  NAMES_HASH = {
  "Akikaze" => "Akikaze",
  "Bean Soup" => "Bean Soup",
  "BlueLightning" => "BlueLightning",
  "Chespin_Craft" => "Chespin_Craft",
  "Gardenette" => "Gardenette",
  "GreenJellyBean" => "GreenJellyBean",
  "Jeremy K" => "Jeremy K",
  "Kaloja" => "Kaloja",
  "Kutas Kitti" => "Kutas Kitti",
  "Low" => "Low",
  "MadMillerMiller" => "MadMillerMiller",
  "MasterMachi" => "MasterMachi",
  "Saltilton" => "Saltilton",
  "SpaceWestern" => "SpaceWestern",
  "LotusLich/Spork" => "LotusLich",
  "stygma" => "stygma",
  "Tyler Jones" => "Tyler Jones",
  "VentesTheFloof" => "VentesTheFloof",
  "FIE.F" => "FIEF",
  "Sunfish" => "Sunfish",
  "CeleryGuy" => "CeleryGuy",
  "blarg" => "blarg",
  "Purple Hat of Awesome" => "FILE",
  "Guill" => "Guill",
  "dipaolo" => "dipaolo",
  "SP0RE" => "SP0RE",
  "Jhams" => "Jhams",
  "Locomotivo" => "Locomotivo",
  "SaraLaGusana" => "SaraLaGusana",
  "Pint Sized Kiwi" => "Pint Sized Kiwi",
  "Nifdoowo" => "Nifdoowo",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  "NAME" => "FILE",
  }
end #class Scene_Credits